name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Find certifi bundle path
        id: cert
        shell: python
        run: |
          import certifi, os
          print(f"::set-output name=cert::{certifi.where()}")

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          $cert = "${{ steps.cert.outputs.cert }}"
          # Windows에선 --add-data 구분자가 ; (세미콜론)
          pyinstaller --onefile --name coupang-bot `
            --add-data "$cert;certifi" `
            script.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coupang-bot-windows
          path: dist/coupang-bot.exe
